services:
  # --- GATEWAY (Nginx HTTPS) ---
  gateway:
    image: nginx:alpine
    container_name: hotel_gateway
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - php
      - grafana

  # --- BACKEND (Node.js API) ---
  php:
    build: ./backend
    container_name: php_server
    environment:
      TELEGRAM_BOT_TOKEN: "8525409568:AAG3saVaLLltmxPLyPKxKeeTUDefK6eldss"
      TELEGRAM_CHAT_ID: "1601238568"
      DB_HOST: "mysql"
      DB_NAME: "smart_hotel_bdd"
      DB_USER: "root"
      DB_PASS: "rootpassword"
      PORT: 80
      TZ: "Europe/Paris" # Correction ici pour l'heure locale
    depends_on:
      - mysql

  # --- DATABASE (MySQL) ---
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_hotel_bdd  
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  # --- FRONTEND (Next.js) ---
  frontend:
    build: ./frontend
    container_name: nextjs_app
    expose:
      - "3000"
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"

# --- GRAFANA (Dashboards) ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_server
    expose:
      - "3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
       - GF_SECURITY_ADMIN_PASSWORD=admin
       - GF_SECURITY_ALLOW_EMBEDDING=true
       - GF_SECURITY_COOKIE_SAMESITE=lax
       - GF_SECURITY_COOKIE_SECURE=false
       - GF_SERVER_PROTOCOL=http
       - GF_SERVER_DOMAIN=192.168.112.158
       - GF_SERVER_ROOT_URL=https://192.168.112.158/grafana/
       - GF_SERVER_SERVE_FROM_SUB_PATH=true
       - GF_SERVER_ENFORCE_DOMAIN=false
       - GF_AUTH_ANONYMOUS_ENABLED=true
       - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    restart: unless-stopped

volumes:
  grafana-storage: