events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    # 1. Redirection HTTP vers HTTPS
    server {
        listen 80;
        server_name 192.168.112.158;
        return 301 https://$host$request_uri;
    }

    # 2. Serveur Principal (HTTPS)
    server {
        listen 443 ssl;
        server_name 192.168.112.158;

        ssl_certificate /etc/nginx/certs/hotel.crt;
        ssl_certificate_key /etc/nginx/certs/hotel.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # --- REDIRECTION ABSOLUE PORTAIL CAPTIF ---
        # Intercepte N'IMPORTE QUELLE requête finissant par wifi.php (même /backend/wifi.php)
        # et redirige proprement le navigateur vers ton interface Next.js
        rewrite ^/.*wifi\.php$ /wifi permanent;

        # --- GRAFANA ---
        location /grafana/ {
            proxy_pass http://grafana_server:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        # --- BACKEND API (Node.js) ---
        location /api/ {
            proxy_pass http://php_server:80;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # --- BACKEND (Ancien PHP) ---
        location /backend/ {
            rewrite ^/backend/(.*)$ /$1 break;
            proxy_pass http://php_server:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # --- ANCIEN ADMIN PHP ---
        location /admin/ {
            proxy_pass http://php_server:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }

        # --- FRONTEND (Next.js) ---
        location / {
            proxy_pass http://nextjs_app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_intercept_errors on;
        }
    }
}